name: Release
on:
  push:
    branches: [ v3-release, release-action ]
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
    - name: Build
      shell: pwsh
      run: ./build.ps1
      id: build-binaries
    - name: Test
      run: dotnet test -c Release

  nuget-package-release:
    needs: build
    name: Nuget package release
    runs-on: windows-latest
    steps:
    - name: Set up nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Publish nuget package
      run: nuget push drop/**/*.nupkg -Source https://docfx.pkgs.visualstudio.com/docfx/_packaging/docs-public-packages/nuget/v3/index.json -ApiKey "${{ secrets.AZURE_DEVOPS_FEED_TOKEN }}"

  github-release:
    name: GitHub release
    needs: build
    runs-on: windows-latest
    steps:
    - name: Create GtiHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.GitAssemblyInformationalVersion }}
        title: Release ${{ env.GitAssemblyInformationalVersion }}
        prerelease: true
        files: |
          drop/docfx-bin/staging/**/*

