name: Docfx V3 Release
on:
  push:
    branches: [ v3-release, release-action ] # for testing
jobs:
  build:
    name: Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
    - name: Donet pack
      # if: ${{ env.BUILD_REASON != 'pull_request' }}
      shell: pwsh
      run: |
        Remove-Item drop -Force -Recurse -ErrorAction Ignore
        dotnet pack -c Release -o drop
    - name: Publish binary packages
      # if: ${{ env.BUILD_REASON != 'pull_request' }}
      shell: pwsh
      run: |
        $packagesBasePath = "drop\docfx-bin"
        New-Item -Path $packagesBasePath -ItemType "directory" -ErrorAction SilentlyContinue
        $stagingPath = "$packagesBasePath\staging"
        New-Item -Path $stagingPath -ItemType "directory" -ErrorAction SilentlyContinue
        $rids = @("win7-x64", "osx-x64", "linux-x64") # Microsoft.ChakraCore doesn't provide win-x64 runtime build, using win7-x64
        foreach ($rid in $rids)
        {
          dotnet publish src\docfx\docfx.csproj -c release -r $rid -o $packagesBasePath/$rid /p:PackAsTool=false
          if ($rid -eq "win7-x64") {
            $version = Invoke-Expression "$packagesBasePath/win7-x64/docfx.exe --version"
            Write-Host "package version: $version"
          }
          $packageName = "docfx-$rid-$version"
          Compress-Archive -Path "$packagesBasePath/$rid/*" -DestinationPath "$stagingPath/$packageName.zip" -Update
          New-Item -Path "$stagingPath" -Name "$packageName.zip.sha256" -Force -ItemType "file" -Value (Get-FileHash "$stagingPath/$packageName.zip").Hash
        }
    - name: Test
      run: dotnet test -c Release
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.GitAssemblyInformationalVersion }}
        title: Version ${{ env.GitAssemblyInformationalVersion }}
        prerelease: true
        files: |
          drop/docfx-bin/staging/**/*
    - name: Publish nuget package
      run: dotnet nuget push --api-key "" --source "" --skip-duplicate

